### ISSUE TITLE
Crear endpoints para el CRUD de líneas de suministro

### ISSUE THREAD

**Issue by geperezzz** [geperezzz/ty-backend-admin#12]
Se deben crear 5 endpoints para la implementación del CRUD. A continuación se detalla el funcionamiento esperado de cada uno

# Endpoint para la creación de una línea de suministro
(Detalles sobre el endpoint)

# Endpoint para la lectura de una línea de suministro
(Detalles sobre el endpoint)

# Endpoint para la lectura de todas las líneas de suministro
(Detalles sobre el endpoint)

# Endpoint para la actualización de una línea de suministro
(Detalles sobre el endpoint)

# Endpoint para la eliminación de una línea de suministro
(Detalles sobre el endpoint)

**Comment by DaikoneKisu** [comment]
Finished and in master!
