### ISSUE TITLE
Crear endpoints para el CRUD de costos de actividades

### ISSUE THREAD

**Issue by geperezzz** [geperezzz/ty-backend-admin#23]
Se deben crear 5 endpoints para la implementación del CRUD. A continuación se detalla el funcionamiento esperado de cada uno

# Endpoint para la creación de un costo
(Detalles sobre el endpoint)

# Endpoint para la lectura de un costo
(Detalles sobre el endpoint)

# Endpoint para la lectura de todos los costos
(Detalles sobre el endpoint)

# Endpoint para la actualización de un costo
(Detalles sobre el endpoint)

# Endpoint para la eliminación de un costo
(Detalles sobre el endpoint)

**Comment by Hector1567XD** [comment]
No estoy deacuerdo
