### ISSUE TITLE
Crear endpoints para el CRUD de empleados

### ISSUE THREAD

**Issue by geperezzz** [geperezzz/ty-backend-admin#3]
Se deben crear 5 endpoints para la implementación del CRUD. A continuación se detalla el funcionamiento esperado de cada uno

# Endpoint para la creación de un empleado
(Detalles sobre el endpoint)

# Endpoint para la lectura de un empleado
(Detalles sobre el endpoint)

# Endpoint para la lectura de todos los empleados
(Detalles sobre el endpoint)

# Endpoint para la actualización de un empleado
(Detalles sobre el endpoint)

# Endpoint para la eliminación de un empleado
(Detalles sobre el endpoint)

**Comment by DaikoneKisu** [comment]
Not finished AJAJAAJAJSHKAD

**Comment by DaikoneKisu** [comment]
Finished
