### ISSUE TITLE
Crear endpoints para el CRUD de vehículos

### ISSUE THREAD

**Issue by geperezzz** [geperezzz/ty-backend-admin#5]
Se deben crear 5 endpoints para la implementación del CRUD. A continuación se detalla el funcionamiento esperado de cada uno

# Endpoint para la creación de un vehículo
(Detalles sobre el endpoint)

# Endpoint para la lectura de un vehículo
(Detalles sobre el endpoint)

# Endpoint para la lectura de todos los vehículo
(Detalles sobre el endpoint)

# Endpoint para la actualización de un vehículo
(Detalles sobre el endpoint)

# Endpoint para la eliminación de un vehículo
(Detalles sobre el endpoint)

**Comment by DaikoneKisu** [comment]
Finished!
