### ISSUE TITLE
Crear endpoints para el CRUD de productos

### ISSUE THREAD

**Issue by geperezzz** [geperezzz/ty-backend-admin#7]
Se deben crear 5 endpoints para la implementación del CRUD. A continuación se detalla el funcionamiento esperado de cada uno

# Endpoint para la creación de un producto
(Detalles sobre el endpoint)

# Endpoint para la lectura de un producto
(Detalles sobre el endpoint)

# Endpoint para la lectura de todos los productos
(Detalles sobre el endpoint)

# Endpoint para la actualización de un producto
(Detalles sobre el endpoint)

# Endpoint para la eliminación de un producto
(Detalles sobre el endpoint)

**Comment by DaikoneKisu** [comment]
Finished and in master!
